workflows:
  android-build:
    name: Build Flappy Box APK
    max_build_duration: 60

    environment:
      vars:
        FLUTTER_VERSION: stable

    scripts:
      - name: Setup Python 3.11
        script: |
          pyenv install 3.11.9 || true
          pyenv global 3.11.9
          python --version

      - name: Install dependencies
        script: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        script: |
          buildozer -v android debug

    artifacts:
      - buildozer/bin/*.apk
