workflows:
  android-build:
    name: Build Flappy Box APK
    max_build_duration: 60
    environment:
      python: "3.11"           # Python 3.11 use karega
      vars:
        FLUTTER_VERSION: stable
    scripts:
      - name: Install dependencies
        script: |
          pip install --upgrade pip
          pip install buildozer
      - name: Build APK
        script: |
          buildozer -v android debug
    artifacts:
      - buildozer/bin/*.apk
