workflows:
  android-build:
    name: Build Flappy Box APK
    max_build_duration: 60

    environment:
      vars:
        PYTHON_VERSION: "3.10"

    scripts:
      - name: Setup Python
        script: |
          pyenv install 3.10.13
          pyenv global 3.10.13
          python --version

      - name: Install dependencies
        script: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      - name: Build APK
        script: |
          buildozer -v android debug

    artifacts:
      - buildozer/bin/*.apk
