workflows:
  android-build:
    name: Build Flappy Box APK
    max_build_duration: 60

    scripts:
      - name: Setup Python 3.11
        script: |
          pyenv install 3.11.9
          pyenv global 3.11.9
          python --version

      - name: Install Buildozer
        script: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        script: |
          buildozer -v android debug

    artifacts:
      - buildozer/bin/*.apk
