workflows:
  android-build:
    name: Build Flappy Box APK
    max_build_duration: 60

    environment:
      vars:
        PYTHON_VERSION: 3.11

    scripts:
      - name: Install dependencies
        script: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        script: |
          buildozer -v android debug

    artifacts:
      - buildozer/bin/*.apk
      
